name: run-wpi-many-tests
on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          show-progress: false
      - name: exec-wpi-many-tests
        run: ./run-cf-tests.sh
        shell: bash
